name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: SonarQube Cloud Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@02ef91109b2d589e757aefcfb2854c2783fd7b19
      uses: SonarSource/sonarcloud-github-action@v4.0.0
      # with:
      #   # Additional arguments to the Sonar Scanner CLI
      #   args: # optional
      #   # Set the sonar.projectBaseDir analysis property
      #   projectBaseDir: # optional
      #   # Version of the Sonar Scanner CLI to use
      #   scannerVersion: # optional, default is 6.2.1.4610
      #   # URL to download the Sonar Scanner CLI binaries from
      #   scannerBinariesUrl: # optional, default is https://binaries.sonarsource.com/Distribution/sonar-scanner-cli
          
      
